services:
  - type: web
    name: school-mg-api
    runtime: node
    autoDeploy: true
    healthCheckPath: /
    buildCommand: bash ./render-build.sh
    startCommand: node --enable-source-maps ./artifacts/api-server/dist/index.mjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER_DATABASE_URL
        sync: false
