export * from "./generated/api";
export type {
  AdminAction,
  AdminIdParameter,
  AdminUser,
  AdminUserCreate,
  AdminUserUpdate,
  GetTeacherFaceStatusParams,
  HealthStatus,
  ListTeacherAttendanceParams,
  ListTeacherLeavesParams,
  MonthParameter,
  PayrollCalculate,
  PayrollReport,
  PayrollReportResultItem,
  StatusParameter,
  StudentAttendanceHolidayCreate,
  StudentAttendanceHolidaySettings,
  StudentAttendanceHolidaySettingsUpdate,
  TeacherAttendanceRecord,
  TeacherAttendanceRecordStatus,
  TeacherAttendanceSettings,
  TeacherAttendanceSettingsDeductionType,
  TeacherAttendanceSettingsUpdate,
  TeacherCheckIn,
  TeacherCheckOut,
  TeacherFaceEnroll,
  TeacherFaceStatus,
  TeacherHolidayCreate,
  TeacherHoliday,
  TeacherIdParameter,
  TeacherLeaveCreate,
  TeacherLeaveStatus,
  TeacherLeave,
  TeacherLeaveUpdate,
  TeacherProfile,
  TeacherProfilePermissions,
} from "./generated/types";
